import type { Category, Task, UserSettings } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'study', name: 'Study', color: '#1479F5', bgColor: '#EBF3FE', isDefault: true },
  { id: 'college', name: 'College', color: '#10B981', bgColor: '#ECFDF5', isDefault: true },
  { id: 'work', name: 'Work', color: '#F97316', bgColor: '#FFF7ED', isDefault: true },
  { id: 'personal', name: 'Personal', color: '#8B5CF6', bgColor: '#F5F3FF', isDefault: true },
  { id: 'health', name: 'Health', color: '#EC4899', bgColor: '#FDF2F8', isDefault: true },
  { id: 'other', name: 'Other', color: '#64748B', bgColor: '#F1F5F9', isDefault: true },
];

export const INITIAL_SETTINGS: UserSettings = {
  user_id: '',
  morning_summary_time: '07:00',
  morning_summary_enabled: true,
  night_review_time: '21:30',
  night_review_enabled: true,
  default_reminder_minutes: 10,
  notifications_enabled: true,
  timezone: 'Asia/Kolkata',
  sound_enabled: true,
  dark_mode: false,
  language: 'English',
};

// Initial realistic tasks matching the reference mockup for 2 Oct 2026 (and today's relative date)
export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    user_id: 'guest-usr',
    title: 'College Assignment',
    description: 'Complete operating systems lab manual submission.',
    date: '2026-10-02',
    time: '09:00 AM',
    task_date: '2026-10-02',
    task_time: '09:00:00',
    completed: true,
    category: 'College',
    reminder_enabled: true,
    reminder_minutes: 10,
    reminder_type: '10_min',
    repeat_type: 'none',
    notes: 'Submit PDF to portal by 10 AM',
    created_at: new Date('2026-10-01T08:00:00Z').toISOString(),
    updated_at: new Date('2026-10-02T09:15:00Z').toISOString(),
  },
  {
    id: 'task-2',
    user_id: 'guest-usr',
    title: 'Python Practice',
    description: 'Solve array and hashmap questions on LeetCode.',
    date: '2026-10-02',
    time: '11:00 AM',
    task_date: '2026-10-02',
    task_time: '11:00:00',
    completed: false,
    category: 'Study',
    reminder_enabled: true,
    reminder_minutes: 10,
    reminder_type: '10_min',
    repeat_type: 'daily',
    notes: 'Practice NumPy and Pandas',
    created_at: new Date('2026-10-01T08:00:00Z').toISOString(),
    updated_at: new Date('2026-10-02T08:00:00Z').toISOString(),
  },
  {
    id: 'task-3',
    user_id: 'guest-usr',
    title: 'Internship Applications',
    description: 'Apply to top 5 tech internship openings with tailored resumes.',
    date: '2026-10-02',
    time: '04:00 PM',
    task_date: '2026-10-02',
    task_time: '16:00:00',
    completed: false,
    category: 'Work',
    reminder_enabled: true,
    reminder_minutes: 15,
    reminder_type: '15_min',
    repeat_type: 'weekdays',
    notes: 'Follow up with recruiters on LinkedIn',
    created_at: new Date('2026-10-01T08:00:00Z').toISOString(),
    updated_at: new Date('2026-10-02T08:00:00Z').toISOString(),
  },
  {
    id: 'task-4',
    user_id: 'guest-usr',
    title: 'Gym',
    description: 'Push day workout: Chest, shoulders, triceps.',
    date: '2026-10-02',
    time: '07:00 PM',
    task_date: '2026-10-02',
    task_time: '19:00:00',
    completed: false,
    category: 'Health',
    reminder_enabled: true,
    reminder_minutes: 30,
    reminder_type: '30_min',
    repeat_type: 'daily',
    notes: 'Drink pre-workout shake at 6:30 PM',
    created_at: new Date('2026-10-01T08:00:00Z').toISOString(),
    updated_at: new Date('2026-10-02T08:00:00Z').toISOString(),
  },
  {
    id: 'task-5',
    user_id: 'guest-usr',
    title: 'Revision',
    description: 'Quick recap of today notes and preparation for tomorrow.',
    date: '2026-10-02',
    time: '09:00 PM',
    task_date: '2026-10-02',
    task_time: '21:00:00',
    completed: false,
    category: 'Personal',
    reminder_enabled: true,
    reminder_minutes: 0,
    reminder_type: 'at_time',
    repeat_type: 'daily',
    notes: 'Review flashcards before bed',
    created_at: new Date('2026-10-01T08:00:00Z').toISOString(),
    updated_at: new Date('2026-10-02T08:00:00Z').toISOString(),
  },
];
